'use client';

import { useState } from 'react';
import { FileDown } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function SpecificMandalReportModal({ 
  mandalId,
  mandalName,
  buttonLabel = "Download PDF",
  buttonClassName = "btn btn-primary",
  buttonStyle = { padding: '0.4rem 1rem', display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.875rem', width: 'auto' }
}: { 
  mandalId: string;
  mandalName: string;
  buttonLabel?: string;
  buttonClassName?: string;
  buttonStyle?: React.CSSProperties;
}) {
  const [isOpen, setIsOpen] = useState(false);
  const [reportGrade, setReportGrade] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  
  const availableColumns = [
    { id: 'schoolName', label: 'School Name' },
    { id: 'village', label: 'Village' },
    { id: 'grade', label: 'Grade' },
    { id: 'headmasterName', label: 'HM Name' },
    { id: 'headmasterPhone', label: 'HM Phone' },
    { id: 'keyPersonName', label: 'Key Person Name' },
    { id: 'keyPersonPhone', label: 'Key Person Phone' },
    { id: 'target', label: 'Target' },
    { id: 'collected', label: 'Collected' },
    { id: 'remaining', label: 'Remaining' },
    { id: 'percentage', label: 'Progress' }
  ];
  
  const [selectedColumns, setSelectedColumns] = useState<string[]>(
    ['schoolName', 'village', 'grade', 'headmasterName', 'target', 'collected', 'percentage']
  );

  const generateReport = async () => {
    if (selectedColumns.length === 0) {
      alert('Please select at least one column');
      return;
    }
    setIsGenerating(true);
    try {
      const query = new URLSearchParams({ mandalId });
      if (reportGrade) query.append('grade', reportGrade);
      
      const res = await fetch(`/api/reports/schools-progress?${query.toString()}`);
      if (!res.ok) throw new Error('Failed to fetch data');
      
      const data = await res.json();
      const report = data.report;
      
      if (!report || report.length === 0) {
        alert('No schools found for this selection.');
        setIsGenerating(false);
        return;
      }
      
      const gradeMap: Record<string, string> = {
        'A+': 'A+ (Vizag Hostel Schools)',
        'A': 'A (Local Corporate Schools)',
        'B': 'B (Local Private Schools)',
        'C': 'C (ZPH Schools)'
      };
      
      const doc = new jsPDF({ orientation: 'landscape' });
      const pageWidth = doc.internal.pageSize.width || doc.internal.pageSize.getWidth();

      // Fetch employee details
      let employeeName = "User";
      let employeeId = "";
      try {
        const meRes = await fetch('/api/auth/me');
        if (meRes.ok) {
          const meData = await meRes.json();
          if (meData.user) {
            employeeName = meData.user.name || employeeName;
            employeeId = meData.user.employeeId || employeeId;
          }
        }
      } catch (e) {
        console.error(e);
      }

      doc.setFontSize(16);
      let title = `School Progress Report - ${mandalName} Mandal`;
      if (reportGrade) title += ` - Grade ${reportGrade}`;
      
      doc.text(title, 14, 20);

      // Top right details
      doc.setFontSize(10);
      doc.text(`Generated by: ${employeeName}`, pageWidth - 14, 16, { align: 'right' });
      doc.text(`Employee ID / Phone: ${employeeId || 'N/A'}`, pageWidth - 14, 21, { align: 'right' });
      
      const tableColumn = availableColumns.filter(c => selectedColumns.includes(c.id)).map(c => c.label);
      
      const tableRows = report.map((row: any) => {
        const rowData: string[] = [];
        availableColumns.forEach(c => {
          if (selectedColumns.includes(c.id)) {
            if (c.id === 'grade') rowData.push(gradeMap[row.grade] || row.grade || '-');
            else if (c.id === 'percentage') rowData.push(`${row.percentage}%`);
            else rowData.push(row[c.id] || '-');
          }
        });
        return rowData;
      });
      
      autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 30,
        theme: 'grid',
        styles: { fontSize: 9, lineColor: [200, 200, 200], lineWidth: 0.1 },
        headStyles: { fillColor: [59, 130, 246] }, // blue-500
        alternateRowStyles: { fillColor: [245, 245, 245] }
      });
      
      doc.save(`School_Report_${mandalName.replace(/\s+/g, '_')}${reportGrade ? '_' + reportGrade : ''}.pdf`);
      setIsOpen(false);
    } catch (err) {
      console.error(err);
      alert('An error occurred while generating the report.');
    }
    setIsGenerating(false);
  };

  return (
    <>
      <button 
        onClick={() => setIsOpen(true)}
        className={buttonClassName} 
        style={buttonStyle}
      >
        <FileDown size={16} /> {buttonLabel}
      </button>

      {isOpen && (
        <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.5)', zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <div style={{ background: 'white', padding: '2rem', borderRadius: '8px', width: '100%', maxWidth: '400px' }}>
            <h3 style={{ marginBottom: '1rem', fontSize: '1.25rem', fontWeight: 600 }}>Download {mandalName} Report</h3>
            
            <div className="form-group" style={{ marginBottom: '1.5rem' }}>
              <label className="form-label" style={{ display: 'block', marginBottom: '0.5rem' }}>Filter by Grade (Optional)</label>
              <select className="form-control" style={{ width: '100%', padding: '0.5rem', borderRadius: '4px', border: '1px solid #ccc' }} value={reportGrade} onChange={e => setReportGrade(e.target.value)}>
                <option value="">All Grades</option>
                <option value="A+">A+ (Vizag Hostel Schools)</option>
                <option value="A">A (Local Corporate Schools)</option>
                <option value="B">B (Local Private Schools)</option>
                <option value="C">C (ZPH Schools)</option>
              </select>
            </div>
            
            <div className="form-group" style={{ marginBottom: '1.5rem' }}>
              <label className="form-label" style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 600 }}>Select Columns</label>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.5rem', maxHeight: '150px', overflowY: 'auto', padding: '0.5rem', border: '1px solid #e2e8f0', borderRadius: '4px', backgroundColor: '#f8fafc' }}>
                {availableColumns.map(col => (
                  <label key={col.id} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.85rem', cursor: 'pointer' }}>
                    <input 
                      type="checkbox" 
                      checked={selectedColumns.includes(col.id)} 
                      onChange={(e) => {
                        if (e.target.checked) setSelectedColumns([...selectedColumns, col.id]);
                        else setSelectedColumns(selectedColumns.filter(id => id !== col.id));
                      }} 
                    />
                    {col.label}
                  </label>
                ))}
              </div>
            </div>
            
            <div style={{ display: 'flex', gap: '1rem', justifyContent: 'flex-end' }}>
              <button className="btn btn-outline" style={{ padding: '0.5rem 1rem', border: '1px solid #ccc', borderRadius: '4px', background: 'transparent', cursor: 'pointer' }} onClick={() => setIsOpen(false)}>
                Cancel
              </button>
              <button className="btn btn-primary" style={{ padding: '0.5rem 1rem', border: 'none', borderRadius: '4px', background: '#3b82f6', color: 'white', cursor: 'pointer' }} onClick={generateReport} disabled={isGenerating}>
                {isGenerating ? 'Generating...' : 'Download'}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
